// flow-typed signature: 9d5ba10cb8c621ce06c9f9ed2e79f338
// flow-typed version: <<STUB>>/redux-forms_v^1.0.0-2/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'redux-forms'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'redux-forms' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'redux-forms/actions' {
  declare module.exports: any;
}

declare module 'redux-forms/dist/redux-forms' {
  declare module.exports: any;
}

declare module 'redux-forms/dist/redux-forms.min' {
  declare module.exports: any;
}

declare module 'redux-forms/lib/__tests__/actions.spec' {
  declare module.exports: any;
}

declare module 'redux-forms/lib/__tests__/arrays.spec' {
  declare module.exports: any;
}

declare module 'redux-forms/lib/__tests__/reducer.spec' {
  declare module.exports: any;
}

declare module 'redux-forms/lib/__tests__/selectors.spec' {
  declare module.exports: any;
}

declare module 'redux-forms/lib/actions' {
  declare module.exports: any;
}

declare module 'redux-forms/lib/arrays' {
  declare module.exports: any;
}

declare module 'redux-forms/lib/containers' {
  declare module.exports: any;
}

declare module 'redux-forms/lib/index' {
  declare module.exports: any;
}

declare module 'redux-forms/lib/reducer' {
  declare module.exports: any;
}

declare module 'redux-forms/lib/selectors' {
  declare module.exports: any;
}

declare module 'redux-forms/lib/shared/__tests__/fieldArrayProps.spec' {
  declare module.exports: any;
}

declare module 'redux-forms/lib/shared/__tests__/fieldProps.spec' {
  declare module.exports: any;
}

declare module 'redux-forms/lib/shared/__tests__/formProps.spec' {
  declare module.exports: any;
}

declare module 'redux-forms/lib/shared/__tests__/getValue.spec' {
  declare module.exports: any;
}

declare module 'redux-forms/lib/shared/__tests__/helpers.spec' {
  declare module.exports: any;
}

declare module 'redux-forms/lib/shared/fieldArrayProps' {
  declare module.exports: any;
}

declare module 'redux-forms/lib/shared/fieldProps' {
  declare module.exports: any;
}

declare module 'redux-forms/lib/shared/formProps' {
  declare module.exports: any;
}

declare module 'redux-forms/lib/shared/getValue' {
  declare module.exports: any;
}

declare module 'redux-forms/lib/shared/helpers' {
  declare module.exports: any;
}

declare module 'redux-forms/selectors' {
  declare module.exports: any;
}

// Filename aliases
declare module 'redux-forms/actions.js' {
  declare module.exports: $Exports<'redux-forms/actions'>;
}
declare module 'redux-forms/dist/redux-forms.js' {
  declare module.exports: $Exports<'redux-forms/dist/redux-forms'>;
}
declare module 'redux-forms/dist/redux-forms.min.js' {
  declare module.exports: $Exports<'redux-forms/dist/redux-forms.min'>;
}
declare module 'redux-forms/lib/__tests__/actions.spec.js' {
  declare module.exports: $Exports<'redux-forms/lib/__tests__/actions.spec'>;
}
declare module 'redux-forms/lib/__tests__/arrays.spec.js' {
  declare module.exports: $Exports<'redux-forms/lib/__tests__/arrays.spec'>;
}
declare module 'redux-forms/lib/__tests__/reducer.spec.js' {
  declare module.exports: $Exports<'redux-forms/lib/__tests__/reducer.spec'>;
}
declare module 'redux-forms/lib/__tests__/selectors.spec.js' {
  declare module.exports: $Exports<'redux-forms/lib/__tests__/selectors.spec'>;
}
declare module 'redux-forms/lib/actions.js' {
  declare module.exports: $Exports<'redux-forms/lib/actions'>;
}
declare module 'redux-forms/lib/arrays.js' {
  declare module.exports: $Exports<'redux-forms/lib/arrays'>;
}
declare module 'redux-forms/lib/containers.js' {
  declare module.exports: $Exports<'redux-forms/lib/containers'>;
}
declare module 'redux-forms/lib/index.js' {
  declare module.exports: $Exports<'redux-forms/lib/index'>;
}
declare module 'redux-forms/lib/reducer.js' {
  declare module.exports: $Exports<'redux-forms/lib/reducer'>;
}
declare module 'redux-forms/lib/selectors.js' {
  declare module.exports: $Exports<'redux-forms/lib/selectors'>;
}
declare module 'redux-forms/lib/shared/__tests__/fieldArrayProps.spec.js' {
  declare module.exports: $Exports<'redux-forms/lib/shared/__tests__/fieldArrayProps.spec'>;
}
declare module 'redux-forms/lib/shared/__tests__/fieldProps.spec.js' {
  declare module.exports: $Exports<'redux-forms/lib/shared/__tests__/fieldProps.spec'>;
}
declare module 'redux-forms/lib/shared/__tests__/formProps.spec.js' {
  declare module.exports: $Exports<'redux-forms/lib/shared/__tests__/formProps.spec'>;
}
declare module 'redux-forms/lib/shared/__tests__/getValue.spec.js' {
  declare module.exports: $Exports<'redux-forms/lib/shared/__tests__/getValue.spec'>;
}
declare module 'redux-forms/lib/shared/__tests__/helpers.spec.js' {
  declare module.exports: $Exports<'redux-forms/lib/shared/__tests__/helpers.spec'>;
}
declare module 'redux-forms/lib/shared/fieldArrayProps.js' {
  declare module.exports: $Exports<'redux-forms/lib/shared/fieldArrayProps'>;
}
declare module 'redux-forms/lib/shared/fieldProps.js' {
  declare module.exports: $Exports<'redux-forms/lib/shared/fieldProps'>;
}
declare module 'redux-forms/lib/shared/formProps.js' {
  declare module.exports: $Exports<'redux-forms/lib/shared/formProps'>;
}
declare module 'redux-forms/lib/shared/getValue.js' {
  declare module.exports: $Exports<'redux-forms/lib/shared/getValue'>;
}
declare module 'redux-forms/lib/shared/helpers.js' {
  declare module.exports: $Exports<'redux-forms/lib/shared/helpers'>;
}
declare module 'redux-forms/selectors.js' {
  declare module.exports: $Exports<'redux-forms/selectors'>;
}
